# Archivo: .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    # ğŸ‘‡ AÃ‘ADE ESTA SECCIÃ“N DE PERMISOS AQUÃ ğŸ‘‡
    permissions:
      contents: write # Permite que el job escriba en el repositorio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Replace API URL Placeholder in HTML ğŸ¤«
        run: |
          sed -i "s|__API_URL_PLACEHOLDER__|${{ secrets.API_KEY_OPENAI }}|g" index.html
      
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .